export * from "./Header/Header";
export * from "./Footer/Footer";
export * from "./CardPokemons/Cardpokemons";
export * from "./Spinner/Spinner";
export * from "./ButtonFilter/ButtonFilter";
export * from "./MemoryTemplate/MemoryTemplate";
export * from "./TresEnRayaTemplate/TresEnRayaTemplate";
export * from "./TopoTemplate/TopoTemplate";
export * from "./Ahorcado/Ahorcado";
